### ISSUE TITLE
Remove is O(n)

### ISSUE THREAD

**Issue by NeilGirdhar** [srkunze/xheap#3]
Remove should be O(log(n)) for a regular heap or O(1) for a Fibonacci heap.

**Comment by srkunze** [comment]
How is the algorithm to remove an arbitrary item from a regular heap in O(log(n))?

How come you refer to Fibonacci heap here?

**Comment by NeilGirdhar** [comment]
Sorry, I got confused with the Fibonacci heap (it's the insert and decrease key that are constant time there).  But remove should be O(log(n)) if you have a pointer to the element being deleted.  If you know you're going to be doing arbitrary removals, then ideally you would have a way to do that.  E.g., providing some kind of handle.

**Comment by srkunze** [comment]
Do you mean XHeap.remove?

XHeap: https://github.com/srkunze/xheap/blob/cac959ec4c0/xheap.py#L179
remove: https://github.com/srkunze/xheap/blob/cac959ec4c0/xheap.py#L216

It has an amortized runtime of O(log n).

**Comment by NeilGirdhar** [comment]
Cool, nice project.

I'll close this issue anyway.  If I get interested again, I'll consider contributing another heap.
